config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/new'

  get 'home/index'

  resources :offers do
    resource :like, module: :offers
  end
  
  resources :users
  root 'home#index', :as => 'home'

  get '/privacy-policy' => 'home#privacypolicy'
  get '/about' => 'home#about'
  get '/terms-of-use' => 'home#termsofuse'
  get '/contact' => 'home#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
    		:recoverable, :rememberable, :trackable, :validatable,
    		:omniauthable, :omniauth_providers => [:facebook]
    has_many :offers, dependent: :destroy, class_name: 'Offer'
    validates_format_of :email, :with => /\A^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.+-]+[a-zA-Z0-9._%+-]\.+[a-zA-Z0-9._%+-]+$\Z/i

  # added like support
  has_many :likes

  def likes?(offer)
    offer.likes.where(user_id: id).any?
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    if user.present?
      user
    else
      user = User.create(name:auth.info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20])
    end
	end

	def self.new_with_session(params, session)
		super.tap do |user|
		  if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
		    user.email = data["email"] if user.email.blank?
		    user.name = data["name"] if user.name.blank?
		  end
		end
	end	

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user ||= 
    	User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < AuthController

	def show
		@user = User.find(params[:id])
		@users = []
		if (current_user.uid == "473418502829853")
			@users = User.all
		end
	end

	def destroy
		if (current_user.uid == "473418502829853")
			User.find(params[:id]).destroy
			flash.now[:success] = "User destroyed"
			redirect_to :home
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p class='item no-top-margin'><br/></p>
<% @user.offers.each do |offer| %>
<div class="box" style="text-align:center;margin-bottom:20px;">
	<div class="text-wrapper" style="text-align:left;border-style:solid;padding-left:50px;padding-right:50px;padding-bottom:50px;">
		<div class="center" style="text-align:center;">
			<% if (current_user == offer.user || current_user.uid == "473418502829853") %>
			<h3><%= link_to 'Edit this offer', edit_offer_path(offer.id) %> | <%= link_to 'Delete', offer_path(offer.id), method: :delete, data: { confirm: 'Are you sure?' } %></h3>
			<% end %>
		</div>
		<%= render partial: 'offers/offer', locals: {offer: offer} %>
	</div>
</div>
<% end %>
<% if ((current_user.uid == "473418502829853") and (current_user.id == @user.id)) %>
	<% @users.each do |u| %>
	<div class="box" style="text-align:center;margin-bottom:20px;">
		<div class="text-wrapper" style="text-align:left;border-style:solid;padding-left:50px;padding-right:50px;padding-bottom:50px;">
			<div class="center" style="text-align:center;">
				<h3 class="item"><%= u.name %></h3>
				<p class="item">#offers: <%= u.offers.length %>, id: <%= u.id %>, uid: <%= u.uid %>, created: <%= u.created_at %></p>
				<img src="http://graph.facebook.com/<%= u.uid %>/picture"></img>
				<p class="item"><%= "todo ban" %> | <%= link_to 'Show', user_path(u.id), method: :get %> | <%= link_to 'Delete', user_path(u.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
			</div>
		</div>
	</div>
	<% end %>
<% end %>