config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/new'

  get 'home/index'

  resources :offers do
    resource :like, module: :offers
  end
  
  resources :users
  root 'home#index', :as => 'home'

  get '/privacy-policy' => 'home#privacypolicy'
  get '/about' => 'home#about'
  get '/terms-of-use' => 'home#termsofuse'
  get '/contact' => 'home#contact'

end

app/views/shared/_flash.html.erb
<!-- MESSAGE SUPPORT -->
<div class="ui page grid notice-bar">
    <% flash.each do |key, value| %>
        <% if value.respond_to?('each') %>
			<div class="ui item <%= key %> message alert alert-danger">
				<% value.each do |element| %>
					<p class="item"><%= element %>.</p>
				<% end %>
			</div>
        <% else %>
            <% if (key == "notice" || key == "success") %>
                <div class="ui item success message alert alert-danger">
                    <p class="item"><%= value %></p>
                </div>
            <% end %>
            <% if (key == "alert" || key == "error") %>
                <div class="ui item error message alert alert-danger">
                    <p class="item"><%= value %></p>
                </div>
            <% end %>
	    <% end %>
	<% end %>
</div>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<div class="ui footer">
    <div class="ui footer-elem">
        <p style="margin: 0em 0em 1em;"><%= link_to 'Privacy Policy', :privacy_policy, :class=>"item" %></p>
        <p style="margin: 0em 0em 1em;"><%= link_to 'Terms of Use', :terms_of_use, :class=>"item" %></p>
        <p style="margin: 0em 0em 1em;"><%= link_to 'About', :about, :class=>"item" %></p>
        <p style="margin: 0em 0em 1em;"><%= link_to 'Contact Us', :contact, :class=>"item" %></p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="ui page grid center nav-holder">
    <nav class="ui inverted menu navbar">
        <div class="left menu nav-elem">
            <%= link_to (image_tag "SubleasyLogo2.png", :class=>"ui logo"), :home, :id =>"subleasy-logo", :class=>"item zero-pad" %>
        </div>
        <div class="right menu nav-elem">
            <%= link_to '<span class="vert"><i class="icon shop"></i>Sublets</span>'.html_safe, offers_path(:school => 'Tufts University'), 'data-no-turbolink' => true, :class=>"item nav-link" %>
            <%= link_to '<span class="vert"><i class="icon home"></i>New Offer</span>'.html_safe, new_offer_path, :class=>"item nav-link" %>
            <% if user_signed_in? %>
                <div class="ui simple item nav-link dropdown">
                    <span class='vert'><%= current_user.name.split.first %><i class="dropdown icon"></i>
                    <img class="ui nav-img zero-pad profile-pic" src='http://graph.facebook.com/<%= current_user.uid %>/picture'></img>
                    </span>
                    <div id='user-menu' class="item menu zero-pad">
                      <%= link_to 'My Offers'.html_safe, current_user, :class=>'ui item nav-link' %>
                      <%= link_to 'Account', edit_user_registration_path, :class => 'ui item nav-link' %>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'ui item nav-link' %>
                    </div>
                </div>
        	<% else %>
              <a href='#' onclick='signinmodalShow()' class='item nav-link'><span class='vert'><i class='facebook square icon'></i>Sign in with Facebook</span></a>
        	<% end %>
        </div>
    </nav>
</div>

app/views/shared/_signinmodal.html.erb
<script type='text/javascript'>
  // fades alert
  $(document).ready(function() {
      $('.alert').delay(5000).fadeOut(1000);
  });
  function signinmodalShow() {
      console.log('test');
      $('#signinmodal').modal('show');
  };
</script>
<div id='signinmodal' class='ui modal'>
  <i class='close icon'></i>
  <div class='box' style='text-align:center;'>
      <div class='text-wrapper modal-styles'>
          <p class='item'><br/></p>
          <p class='item'>By using this website you agree to the <%= link_to 'Terms of Use', :terms_of_use %> and the <%= link_to 'Privacy Policy', :privacy_policy %>.</p>
          <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => 'item' %>
          <p class='item'><br/></p>
      </div>
  </div>
</div>