config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/new'

  get 'home/index'

  resources :offers do
    resource :like, module: :offers
  end
  
  resources :users
  root 'home#index', :as => 'home'

  get '/privacy-policy' => 'home#privacypolicy'
  get '/about' => 'home#about'
  get '/terms-of-use' => 'home#termsofuse'
  get '/contact' => 'home#contact'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
	belongs_to :user, class_name: "User", :foreign_key => "user_id"

	# added like support
	has_many :likes

	before_validation :squish_whitespace

	validates_presence_of :user,:image,
					:line1,:city,:state,:zip,:rent,:start_date,
					:end_date,:school,:description,:latitude,:longitude
	validates :image, :format => URI::regexp(%w(http https))
	validate :dates_make_sense 

	validates_length_of :description, :maximum => 750
	validates_length_of :line1, :maximum => 100
	validates_length_of :line2, :maximum => 100
	validates_length_of :city, :maximum => 50
	validates_length_of :image, :maximum => 255

	def dates_make_sense
		errors.add(:start_date, "and end date need to make logical sense") if (start_date < Date.today) || (start_date > end_date)
	end

	def squish_whitespace
		self.image = self.image.squish()
		self.line1 = self.line1.squish().split.map(&:capitalize).join(' ')
		self.line2 = self.line2.squish()
		self.city = self.city.squish().split.map(&:capitalize).join(' ')
	end

	def full_address
		return (self.line1 + " " + self.city + " " + self.state).squish()
	end		
end

app/controllers/offers/likes_controller.rb
class Offers::LikesController < AuthController
  before_action :set_offer

  def create
    @offer.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @offer }
      format.js
    end
  end

  def destroy
    @offer.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @offer }
      format.js
    end
  end

  private

    def set_offer
      @offer = Offer.find(params[:offer_id])
    end
end

app/controllers/offers_controller.rb
class OffersController < AuthController
	before_action :correct_user, only: [:edit, :update, :destroy]
	before_action :set_offer, only: [:show, :edit, :update, :destroy]
	skip_before_action :authenticate_user!, only: [:index, :show]

	def index
		if (params[:school].size == 0)
			params[:school] = "Tufts University"
		end
		@offers = Offer.where(school: params[:school])
		if (@offers.size == 0)
			flash.now[:error] = "Error! Your school was not found."
		end
	end

	def show
		#@offers = Offer.where(latitude: @offer.latitude,longitude: @offer.longitude)
		@offer = Offer.find(params[:id])
	end

	def new
		@offer = Offer.new
	end

	def edit
	end

	def create
		@offer = current_user.offers.build(offer_params)

		respond_to do |format|
			if @offer.save
				flash.now[:success] = "Success! Your offer has been posted."
				format.html {redirect_to @offer }
				format.json {render :show, status: :created, location: @post }
			else
				flash.now[:error] = @offer.errors.full_messages
				format.html { render :new }
				format.json { render json: @offer.errors.full_messages, status: :unprocessable_entity }
			end
		end
		# if @offer.save
		# 	flash[:success] = "Success! Your offer has been posted."
		# 	redirect_to @offer
		# else
		# 	flash[:error] = @offer.errors.full_messages
		# 	render :new
		# end
	end

	def update
		respond_to do |format|
			if @offer.update(offer_params)
				flash.now[:success] = "Success! Your offer has been updated."
				format.html { redirect_to @offer }
				format.json { render :show, status: :ok, location: @offer }
			else
				flash.now[:error] = @offer.errors.full_messages
				format.html { render :edit }
				format.json { render json: @offer.errors.full_messages, status: :unprocessable_entity }
			end
		end

		# if @offer.update(offer_params)
		# 	flash[:success] = "Success! Your offer has been updated."
		# 	redirect_to @offer
		# else
		# 	flash[:error] = @offer.errors.full_messages
		# 	render :edit
		# end
	end

	def destroy
		@offer.destroy
		respond_to do |format|
			flash.now[:success] = "Offer was successfully deleted."
			format.html { redirect_to offers_path }
			format.json { head :no_content }
		end
	end

	private
		def set_offer
			@offer = Offer.find(params[:id])
		end

		def offer_params
			params.require(:offer).permit(:user,:image,
					:line1,:line2,:city,:state,:zip,:rent,:start_date,
					:end_date,:water,:electric,:gas,:heat,:internet,:washdry,
					:aircond,:handicap,:parking,:interested,:school,:description,
					:furnished)
		end

		def correct_user
			@user = Offer.find(params[:id]).user
			redirect_to(:home) unless (@user == current_user || current_user.uid == "473418502829853")
		end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for @offer do |f| %>
	<%= f.hidden_field :interested, value: 0 %>
	<table class="new-form-table">
		<tr>
			<td><h3 class="form-header">Where is your sublet?</h3></td>
		</tr>
  		<tr>
			<td class="item half"><%= f.text_field :line1, :required => true, :placeholder => 'Address Line 1' %></td>
		    <td class="item half"><%= f.text_field :line2, :placeholder => 'Address Line 2' %></td>
		</tr>
		<tr>
			<td class="item"><%= f.text_field :city, :required => true, :placeholder => 'City' %></td>
		    <td class="item"><%= f.select :state, options_for_select(us_states),{:include_blank => 'State'}, class:'form_control', :required => true %></td>
    		<td class="item"><%= f.number_field :zip, within: 0...99999, :required => true, :placeholder => 'Zip' %></td>
    	</tr>
	</table>
	<table class="new-form-table">
		<tr>
			<td><h3 class="form-header">Tell us a bit about your sublet.</h3></td>
		</tr>
		<tr>
			<td class="item half-line"><%= f.number_field :rent, within: 0...9999, :required => true, :placeholder => 'Rent' %></td>
  			<td class="item half-line"><%= f.text_field :image, :placeholder => 'Link to photo for listing' %></td>
  			<td class="item half-line"><%= f.select :school, options_for_select(supported_schools),{:include_blank => 'School'}, class:'form_control', :required => true %></td>
		</tr>
		<tr>
			<td class="item"><%= f.text_area :description, :maxlength => '750', size: '40x5', :required => true, :placeholder => 'Description (max 750 characters)' %></td>
		</tr>
	</table>
	<table class="new-form-table">
		<tr>
			<td><h3 class="form-header">What start and end dates are you hoping for?</h3></td>
		</tr>
		<tr>
			<td class="item half-line">
				<%= f.date_select :start_date, :required => true %>
			</td>
			<td class='item half-line'>through</td>
			<td class="item half-line">
				<%= f.date_select :end_date, :required => true %>
			</td>
		</tr>
	</table>
	<table class="new-form-table">
		<tr>
			<td><h3 class="form-header">What utilities are included?</h3></td>
		</tr>
		<tr>
			<td class="item">
				<%= f.check_box :water %><%= f.label :water, 'Water' %>
				<%= f.check_box :electric %><%= f.label :electric, 'Electric' %>
				<%= f.check_box :gas %><%= f.label :gas, 'Gas' %>
				<%= f.check_box :heat %><%= f.label :heat, 'Heat' %>
				<%= f.check_box :internet %><%= f.label :internet, 'Internet' %></td>
		</tr>
	</table>
	<table class="new-form-table">
		<tr>
			<td><h3 class="form-header">Other information?</h3></td>
		</tr>
		<tr>
			<td class="item multi-line">
				<%= f.check_box :washdry %><%= f.label :washdry, 'Washer/dryer' %>
				<%= f.check_box :aircond %><%= f.label  :aircond, 'Air conditioning' %>
				<%= f.check_box :handicap %><%= f.label  :handicap, 'Handicap accessible' %></td>
			<td class="item">
				<%= f.check_box :parking %><%= f.label :parking, 'Parking space' %>
				<%= f.check_box :furnished %><%= f.label :furnished , 'Furnished'%></td>
		</tr>
	</table>
	<table class="new-form-table">
		<tr>
    		<td class="item"><%= f.submit %></td>
    	</tr>
	</table>
<% end %>

app/views/offers/_likes.html.erb
<% if user_signed_in? %>
	<% if current_user.likes?(offer) %>
  	<div class='ui primary button'>
  			<%= offer.likes.count %>
  	    <i class="thumbs outline up icon"></i>
  	    <%= link_to "<span style='color:white;'>Liked!</span>".html_safe, offer_like_path(offer), method: :delete, remote: true, :class=>'item' %>
  	</div>
  <% else %>
  	<div class='ui primary button'>
  	    <%= offer.likes.count %>
  	    <i class="thumbs outline up icon"></i>
  	    <%= link_to "<span style='color:white;'>Like this sublet?</span>".html_safe, offer_like_path(offer), method: :post, remote: true, :class=>'item' %>
  	</div>	
  <% end %>
<% else %>
	<div class='ui primary button'>
		<%= offer.likes.count %>
    <i class="thumbs outline up icon"></i>
    <a href='#' onclick='signinmodalShow()' class='item'><span style='color:white;'>Like this sublet?</span></a>
	</div>
<% end %>

app/views/offers/_offer.html.erb
<div class='center' style='text-align:center;'>
	<h2><a><%= link_to offer.line1 + ' ' + offer.line2, offer_path(offer.id) %></a></h2>
	<h3>
		<% if user_signed_in? %>
		<div class='ui primary button'>
		    <i class='in cart icon'></i><a href='https://www.facebook.com/app_scoped_user_id/<%= offer.user.uid %>' class='item'><span style='color:white;'>Contact Seller</span></a>
		</div>
		<% end %>
		<div class='offer_<%= offer.id %>_likes' style='display:inline-block'>
			<%= render partial: 'offers/likes', locals: {offer: offer} %>
		</div>
	</h3>
</div>
<div class='ui grid'>
	<div class='ui eight wide column'>
		<div class='ui center image-holder' style='text-align:center;'>	
			<img src='<%= offer.image %>' alt='No image available for this sublet' min-height='200px'></img>
		</div>
		<h3>Address</h3>
		<p class='item'><%= offer.line1 %> <%= offer.line2 %></p>
		<p class='item'><%= offer.city %>, <%= offer.state %>. <%= offer.zip %></p>
		<h3>Rental information</h3>
		<p class='item'>$<%= offer.rent %>/mo</p>
		<p class='item' style='margin-top: 0px;'><%= offer.start_date.strftime('%a %d %b %Y') %> - <%= offer.end_date.strftime('%a %d %b %Y') %></p>
	</div>
	<div class='ui eight wide column'>
		<p style='display:none;'></p>
		<h3 class='no-top-margin'>Description</h3>
		<p class='item' style='word-wrap: break-word;'><%= offer.description %></p>
		<h3 class='no-top-margin'>Utility information</h3>
		<table class='item' style='line-height: 1.33rem; margin-bottom: 1rem;'>
			<tr class='buffered'>
				<td>Water:</td><td><%= offer.water ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<p><td>Internet:</td><td><%= offer.internet ? 'Yes' : 'No' %></td></p>
			</tr>
			<tr class='buffered'>
				<td>Electric:</td><td><%= offer.electric ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<td>Heat:</td><td><%= offer.heat ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<td>Gas:</td><td><%= offer.gas ? 'Yes' : 'No' %></td>
			</tr>
		</table>
		<h3 class='no-top-margin'>Other</h3>
		<table class='item'>
			<tr class='buffered'>
				<td>Washer/dryer?</td><td><%= offer.washdry ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<td>Air conditioning?</td><td><%= offer.aircond ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<td>Handicap?</td><td><%= offer.handicap ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<td>Parking?</td><td><%= offer.parking ? 'Yes' : 'No' %></td>
			</tr>
			<tr class='buffered'>
				<td>Furnished?</td><td><%= offer.furnished ? 'Yes' : 'No' %></td>
			</tr>
		</table>
	</div>
</div>

app/views/offers/edit.html.erb
<div class="wrapper" style="text-align:center;width:800px;margin:auto;">
	<h1 class='page-title'>Edit Offer</h1>
	<div class="text-wrapper" style="text-align:left;border-style:solid;padding-left:50px;padding-right:50px;padding-bottom:50px;padding-top:50px;">
	<%= render 'form' %>
	</div> 
</div>

app/views/offers/index.html.erb
<div id='map-container'>
 	<div id='map-canvas'></div>
</div>
<div class='ui wrapper offers-index' style='text-align:center;'>
	<!-- FILTERS -->
	<div class='ui'>
		<h3>Find your dream sublet...</h3>
		<p class='item no-top-margin'>Markers on the map are colored by monthly rent, from <span style='color:green'>low</span> to <span style='color:red'>high</span></p>
		<div id='filters'>
			<p class='item' style='margin-bottom:1em;'>Max rent</p>
			<p class='filter-item item'><input class='item' type='number' id='max-rent'></p>
			<p class='item'>Start date</p>
			<p class='filter-item item'><%= date_select 'start-date', nil, { :start_year => Date.today.year, :default => Time.now, :prompt => { day: 'Day', month: 'Month', year: 'Year'}} %></p>
			<p class='item'>End date</p>
			<p class='filter-item item no-top-margin'><%= date_select 'end-date', nil, { :start_year => Date.today.year, :default => Time.now, :prompt => { day: 'Day', month: 'Month', year: 'Year'}} %></p>
		</div>
		<div class='ui button-group'>
			<div class='ui sketchButton'>
				<p id='filtergo' class='item'>Go</p>
			</div>
			<div class='ui sketchButton reset-button'>
				<p id='reset-filters' class='item'>Reset</p>
			</div>
		</div>
	</div>
</div>
	<!-- MODALS -->
<div>
 	<% @offers.each do |offer| %>
 	<div id='<%= offer.id %>modal' class='ui' style='display:none; text-align:center;'>
		<div class='text-wrapper modal-styles'>
			<%= render partial: 'offer', locals: {offer: offer } %>
		</div>
	</div>
	<% end %>
</div>

<!-- This is the modal that is shown. Data is appended to inner div. -->
<div>
 	<div id='offersmodal' class='ui modal'>
 		<i class='close icon'></i>
		<div style='text-align:center;'>
		</div>
	</div>
</div>

<script type='text/javascript'>
	function test(value) {
		console.log('test ' + value)
	}
	//-------------------------------------------//
	//		Google maps stuff
	//
	var map;
	var markers = [];
	function initialize() {
	 	var mapOptions = {
	    	zoom: 14,
		    center: new google.maps.LatLng(42.407484, -71.119023)
	  	};
	  	map = new google.maps.Map(document.getElementById('map-canvas'),
	      mapOptions);
		generateMarkersByParameter(offers, 'rent')
	}

	function generateMarkersByParameter(array, parameter) {
		deleteMarkers()
		if (!array.length) return;
		minP = array[0][parameter]
		maxP = array[array.length-1][parameter]
		for (var i = 0; i < array.length; i++) {
	  	  	var pinImage = new google.maps.MarkerImage('http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|' + newColorFunc(array[i][parameter], minP, maxP));
	   	  //       new google.maps.Size(21, 34),
	   	  //       new google.maps.Point(0,0),
	   	  //       new google.maps.Point(10, 34));
	   	  	// var pinImage = newColorFunc(array[i][parameter], minP, maxP);
	  	  	var marker = new google.maps.Marker({
			    	position: new google.maps.LatLng(array[i].latitude, array[i].longitude),
			    	map: map,
			    	icon: pinImage,
			    	url: '#' + array[i].id.toString(),
			    	title: array[i].line1
	   	  	});
	   	  // modal listener
		   	google.maps.event.addListener(marker, 'click', function() {
		   			//for (var i = 0; i < offers_filtered.length; i++)
		   			var offersmodal = $('#offersmodal');
		   			var offersmodal_inner = $('#offersmodal > div');
		   			offersmodal_inner.empty();
		   			// if we have multiple offers display text indicating so

		   			offers_for_modal = genOfferModal(this.position.lat(), this.position.lng());
		   			//console.log(this.position.lat(),this.position.lng())
		   			//console.log(offers_for_modal);
		   			if (offers_for_modal.length > 1) {
		   				// TODO make this a popup that goes away
		   				offersmodal_inner.append("<p class='item' style='padding-top:1em; margin-bottom:1em;'>There are multiple sublets available at this location. Scroll down to view.</p>");
		   				// if (offers_for_modal.length > 1) {
		   				// 	offersmodal.modal('show');
		   				// 	$('#offersmodal > div').append("<p class='item'><br/>There are multiple sublets available at this location. Loading...<br/></p>").delay(2000).delay(10, function() { $('#offersmodal > div > p').fadeOut('slow', function () { $('#offersmodal > div').empty(function() { for (var i = 0; i < offers_for_modal.length; i++) {
		   				// 				// this is the rendered partial
		   				// 	    	var elem = $('#' + offers_for_modal[i].id.toString() + 'modal > div');
		   				// 	    	elem.clone().appendTo(offersmodal_inner);
		   				// 	     }}) })});
		   			}
		   			for (var i = 0; i < offers_for_modal.length; i++) {
		   				// this is the rendered partial
		   	    	var elem = $('#' + offers_for_modal[i].id.toString() + 'modal > div');
		   	    	elem.clone().appendTo(offersmodal_inner);
		   	    }
		   	    offersmodal.modal('show');
		   	    	// if there are multiple modals to show, then pull the
		   	    	// text for the other modals and 
		   	  		// generate the modal dynamically instead of having all these dumb modal show comments... much better!!!

		   	});
		   	markers.push(marker)
   		}
   	}

   	function deleteMarkers() {
	   	for (var i = 0; i < markers.length; i++) {
	   	  markers[i].setMap(null);
	   	}
	   	markers = []
   	}

	function componentToHex(c) {
	    var hex = c.toString(16);
	    return hex.length == 1 ? '0' + hex : hex;
	}

	// function rainbowColor(val, min, max)
	// {
	// 	var hue = Math.floor((max - val) * 120 / max);  // go from green to red
	// 	var saturation = Math.abs(val - ((max - min)/2))/((max - min)/2);   // fade to white as it approaches 50
	//     // var i = ((val - min) * (max - min) / (max - min));
	//     // var r = Math.round(Math.sin(0.024 * i + 0) * 127 + 128);
	//     // var g = Math.round(Math.sin(0.024 * i + 2) * 127 + 128);
	//     // var b = Math.round(Math.sin(0.024 * i + 4) * 127 + 128);
	//     // return componentToHex(r) + componentToHex(g) + componentToHex(b);
	// }

	var newColorFunc = function(val, min, max) {
		var relativeValue = (val - min)/(max - min + 0.001);
		console.log(val, relativeValue);
		if (relativeValue < .25) {
			return '00ff00';
		}
		else if (relativeValue < .5) {
			return 'ffff00';
		}
		else if (relativeValue < .75) {
			return 'ffa500';
		}
		else {
			return 'ff0000';
		}
		
	}

	var hsv2rgb = function(val, min, max) {
	  // adapted from http://schinckel.net/2012/01/10/hsv-to-rgb-in-javascript/
	  var h = Math.floor(((max - min) - (val - min)) * 120 / (max - min + 0.001));
      var s = Math.abs((val - min) - ((max - min)/2))/((max - min + 0.001)/2);
      var v = 1;
	  var rgb, i, data = [];
	  if (s === 0) {
	    rgb = [v,v,v];
	  } else {
	    h = h / 60;
	    i = Math.floor(h);
	    data = [v*(1-s), v*(1-s*(h-i)), v*(1-s*(1-(h-i)))];
	    switch(i) {
	      case 0:
	        rgb = [v, data[2], data[0]];
	        break;
	      case 1:
	        rgb = [data[1], v, data[0]];
	        break;
	      case 2:
	        rgb = [data[0], v, data[2]];
	        break;
	      case 3:
	        rgb = [data[0], data[1], v];
	        break;
	      case 4:
	        rgb = [data[2], data[0], v];
	        break;
	      default:
	        rgb = [v, data[0], data[1]];
	        break;
	    }
	  }
	  return rgb.map(function(x){
	    return ('0' + Math.round(x*255).toString(16)).slice(-2);
	  }).join('');
	};

	google.maps.event.addDomListener(window, 'load', initialize);
	//
	//
	//-------------------------------------------//
	//		Sorting, filtering, other features with our data
	//
	offers = <%=raw @offers.to_json %>
	offers = sortByKey(offers, 'rent')
	offers_filtered = offers
	offers_for_modal = offers_filtered
	const TOLERANCE = 0.000001 // Floating point issues with lat/lng
	// TODO mismatched start/end date, illogical start/end date


	function sortByKey(array, key) {
	    return array.sort(function(a, b) {
	        var x = a[key]; var y = b[key];
	        return ((x < y) ? -1 : ((x > y) ? 1 : 0));
	    });
	}

	$(document).ready(function() {
		$('#max-rent').keydown(function (event) {
			if (event.keyCode == 13) {
				runFilters();
			}
		});
		$('#start-date').keydown(function (event) {
			if (event.keyCode == 13) {
				runFilters();
			}
		});
		$('#end-date').keydown(function (event) {
			if (event.keyCode == 13) {
				runFilters();
			}
		});
		$('#filtergo').click(function() {
			runFilters();
		});
		$('#reset-filters').click(function() {
			$('#max-rent').val('');
			$('#filters [name*="start-date"] :selected').each(function() { 
				$(this).removeAttr('selected');
			});
			$('#filters [name*="end-date"] :selected').each(function() { 
				$(this).removeAttr('selected');
			});
			generateMarkersByParameter(offers, 'rent');
		});
	});

	function runFilters() {
		var rentFilter = Number($('#max-rent').val());
		var startDateFilter = '';
		$('#filters [name*="start-date"] :selected').each(function() { 
			var temp = $(this).val();
			if (temp.length == 1) {
				temp = '0' + temp;
			}
			startDateFilter+=temp+'-'; 
		});
		startDateFilter = startDateFilter.slice(0, -1);

		var endDateFilter = '';
		$('#filters [name*="end-date"] :selected').each(function() { 
			var temp = $(this).val();
			if (temp.length == 1) {
				temp = '0' + temp;
			}
			endDateFilter+=temp+'-'; 
		});
		endDateFilter = endDateFilter.slice(0, -1);

		var offersFiltered = offers.slice(0);

		console.log(rentFilter);
		console.log(offersFiltered)

		if (rentFilter != 0) {
			offersFiltered = offersFiltered.filter(function(item) { return item['rent'] <= rentFilter});	
		}
		if (startDateFilter != endDateFilter) {
			offersFiltered = offersFiltered.filter(function(item){return ((item['start_date'] <= startDateFilter) && (item['end_date'] >= endDateFilter))});
		}
		console.log(offersFiltered)
		generateMarkersByParameter(offersFiltered, 'rent');
	}

	function genOfferModal(lat,lng) {
		offers_for_modal = offers_filtered.filter(function(offer){
				return (Math.abs(lat-offer.latitude)+Math.abs(lng-offer.longitude))<TOLERANCE
			})
		return offers_for_modal
	}
</script>

<!-- var pinColor = 'FE7569';
var pinImage = new google.maps.MarkerImage('http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|' + pinColor,
    new google.maps.Size(21, 34),
    new google.maps.Point(0,0),
    new google.maps.Point(10, 34))
var pinShadow = new google.maps.MarkerImage('http://chart.apis.google.com/chart?chst=d_map_pin_shadow',
    new google.maps.Size(40, 37),
    new google.maps.Point(0, 0),
    new google.maps.Point(12, 35))
var marker = new google.maps.Marker({
            position: new google.maps.LatLng(0,0), 
            map: map,
            icon: pinImage,
            shadow: pinShadow
        }) -->

app/views/offers/new.html.erb
<div class="wrapper">
<div class="text-wrapper">
<h1 class='page-title'>Make an offer they can't refuse</h1>
<%= render 'form' %>
</div> 
</div>

app/views/offers/show.html.erb
<p class='item no-top-margin'><br/></p>
<div class="wrapper" style="text-align:center;margin:auto;">
	<div class="text-wrapper" style="text-align:left;border-style:solid;padding-left:50px;padding-right:50px;padding-bottom:50px;">
		<div class="center" style="text-align:center;">
			<% if (user_signed_in? && (current_user == @offer.user || current_user.uid == "473418502829853")) %>
				<h3><%= link_to 'Edit this offer', edit_offer_path(@offer.id) %> | <%= link_to 'Delete', offer_path(@offer.id), method: :delete, data: { confirm: 'Are you sure?' } %></h3>
			<% end %>
		</div>
		<%= render partial: 'offer', locals: {offer: @offer} %>
	</div>
</div>